#!/usr/bin/env bash
# OSKAR — Server Secrets Provisioning Script (PRE-11)
# Run as root on the OSKAR Linux VM before first deploy.
# Prompts interactively — secrets never passed as arguments (no shell history exposure).
#
# Usage:
#   sudo bash scripts/setup-server-secrets.sh
#
# What it does:
#   1. Creates /etc/oskar/ if absent
#   2. Writes /etc/oskar/secrets.env from interactive prompts
#   3. Sets ownership root:oskar-app, mode 0640
#   4. Prints SHA-256 checksum — record this in ai/evidence/decision-log.md

set -euo pipefail

SECRETS_DIR="/etc/oskar"
SECRETS_FILE="${SECRETS_DIR}/secrets.env"
SERVICE_GROUP="oskar-app"

# ── Preflight ─────────────────────────────────────────────────────────────────

if [[ "${EUID}" -ne 0 ]]; then
    echo "ERROR: This script must be run as root (sudo)." >&2
    exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  OSKAR — Server Secrets Provisioner (PRE-11)             ║"
echo "║  Secrets go to: ${SECRETS_FILE}         ║"
echo "║  Ownership: root:oskar-app  Mode: 0640                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "You will be prompted for each secret. Input is hidden."
echo "Secrets are written to ${SECRETS_FILE} only — not logged, not echoed."
echo ""

# ── Prompt helper ─────────────────────────────────────────────────────────────

prompt_secret() {
    local var_name="$1"
    local description="$2"
    local value=""
    local confirm=""

    while true; do
        read -rsp "  ${var_name} (${description}): " value
        echo ""
        read -rsp "  ${var_name} (confirm): " confirm
        echo ""
        if [[ "${value}" == "${confirm}" ]]; then
            break
        fi
        echo "  ✗ Values do not match. Try again."
    done

    printf '%s="%s"\n' "${var_name}" "${value}" >> "${SECRETS_FILE}"
}

# ── Create directory and empty file ──────────────────────────────────────────

mkdir -p "${SECRETS_DIR}"
: > "${SECRETS_FILE}"   # truncate / create

cat >> "${SECRETS_FILE}" << 'HEADER'
# /etc/oskar/secrets.env
# Generated by scripts/setup-server-secrets.sh (PRE-11)
# Owner: root:oskar-app  Mode: 0640
# DO NOT commit this file. DO NOT store in Docker image layers.
# Mounted read-only into oskar-app and oskar-worker containers via env_file directive.
HEADER

echo ""
echo "── PostgreSQL ────────────────────────────────────────────────"
prompt_secret "OSKAR_DB_PASSWORD" "PostgreSQL password for oskar application user"

echo ""
echo "── JWT ───────────────────────────────────────────────────────"
echo "  Tip: generate with: openssl rand -hex 32"
prompt_secret "JWT_SECRET_KEY" "JWT signing key, minimum 256-bit (64 hex chars)"

echo ""
echo "── Redis ─────────────────────────────────────────────────────"
prompt_secret "REDIS_PASSWORD" "Redis AUTH password"

echo ""
echo "── Active Directory (LDAPS) ──────────────────────────────────"
prompt_secret "LDAP_BIND_PW" "Service account password for LDAPS bind"

echo ""
echo "── Celery ────────────────────────────────────────────────────"
echo "  Tip: generate with: openssl rand -hex 32"
prompt_secret "CELERY_SECURITY_KEY" "Celery task signing key"

echo ""
echo "── SMTP (Sprint 2 — enter placeholder if not yet configured) ─"
prompt_secret "SMTP_PASSWORD" "Corporate SMTP relay password"

# ── Lock down permissions ─────────────────────────────────────────────────────

# Ensure the service group exists (create if absent)
if ! getent group "${SERVICE_GROUP}" > /dev/null 2>&1; then
    groupadd --system "${SERVICE_GROUP}"
    echo "  Created system group: ${SERVICE_GROUP}"
fi

chown "root:${SERVICE_GROUP}" "${SECRETS_FILE}"
chmod 0640 "${SECRETS_FILE}"

# ── Checksum ──────────────────────────────────────────────────────────────────

CHECKSUM=$(sha256sum "${SECRETS_FILE}" | awk '{print $1}')

echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  ✓ Secrets written to: ${SECRETS_FILE}"
echo "  ✓ Ownership:          root:${SERVICE_GROUP}"
echo "  ✓ Permissions:        $(stat -c '%a' "${SECRETS_FILE}")"
echo ""
echo "  SHA-256: ${CHECKSUM}"
echo ""
echo "  IMPORTANT: Record this checksum in ai/evidence/decision-log.md"
echo "  Format:  $(date +%Y-%m-%d) | secrets.env provisioned on OSKAR VM | SHA-256: ${CHECKSUM}"
echo "══════════════════════════════════════════════════════════════"
echo ""
